# This file holds the configurations train a normalizing flow by the main.py file
# You can set multiple configurations and the main file will loop trough them and perform diferent trainings

data_inputs:
    alpha_ref  : 0.0210
    lambda_ref : 1350
    ztrue_ref  : 25.0
    P_ref      : 0.9070
    T_ref      : 20.6
    sim_map    : simulation_map.yaml
    data_map   : data_map.yaml
    alpha_val  : 0.0218
    lambda_val : 1650
    ztrue_val  : 25.0
    P_val      : 0.9170
    T_val      : 20.6


configuration_2026_lime_v1:
    encoder_hidden_dim   : 64
    encoder_output_dim   : 32
    encoder_n_layers     : 2
    encoder_dropout      : 0.1
    flow_n_layers        : 6
    flow_hidden_dim      : 128
    flow_context_dim     : 32
    initial_lr           : 5.0e-4
    batch_size           : 50
    sigma_mmd            : 1.0
    lambda_mom           : 0
    standardize          : 1